# Generated by Django 5.0.4 on 2024-05-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeven', models.CharField(max_length=100)),
                ('desceven', models.CharField(blank=True, max_length=20, null=True)),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
