# Generated by Django 5.0.4 on 2024-05-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
